version: '3.5'

services:
    gitlab:
        hostname: ${gitlab_url}
        environment: 
            GITLAB_OMNIBUS_CONFIG: |
                external_url ${gitlab_url_https}
                gitlab_rails['gitlab_shell_ssh_port'] = 2222
                nginx['listen_port'] = 80
                nginx['listen_https'] = false
                nginx['proxy_set_headers'] = {
                    'X-Forwarded-Proto' => 'https',
                    'X-Forwarded-Ssl' => 'on',
                    'Host' => ${gitlab_url}
                }
                registry['enable'] = true
                registry_external_url ${gitlab_registry_url_https}
                registry_nginx['listen_port'] = 80
                registry_nginx['listen_https'] = false
        labels: 
            - traefik.frontend.rule=Host:${gitlab_url}
            - ghosts.host=${gitlab_url}