version: '3.5'

services: 
    gitlab:
        hostname: ${gitlab_url}
        environment: 
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'https://${gitlab_url}'
                registry_external_url 'https://${gitlab_registry_url}'
        labels: 
            - traefik.frontend.rule=Host:${gitlab_url},${gitlab_registry_url}
            - ghosts.host=${gitlab_url},${gitlab_registry_url}