version: '3.5'

networks: 
    default: {}
    server_proxy:
        external: true

volumes: 
    data:
        name: gitlab_data
    logs: 
        name: gitlab_logs

services: 
    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab
        restart: unless-stopped
        ports: 
            - "2222:22"
        networks: 
            - default
            - server_proxy
        volumes: 
            - ./.docker/gitlab/config/gitlab.rb:/etc/gitlab/gitlab.rb
            - logs:/var/log/gitlab/
            - data:/var/opt/gitlab/
        labels: 
            - traefik.enable=true
            - traefik.port=80
            - traefik.frontend.redirect.entryPoint=https
            - traefik.docker.network=server_proxy
            - ghosts.category=~Repository
            - ghosts.description=GitLab CE server
            - ghosts.proto=https